workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ( $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "feature/ci_with_new_linker" || $CI_COMMIT_BRANCH =~ /^pr\// )

variables:
  SLURM_ACCOUNT: hpc-prf-cifi
  GIT_SUBMODULE_STRATEGY: recursive

default:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  before_script:
    - module reset
    - ml fpga lang tools devel Python xilinx/vivado/25.1 UnZip gitlab-cli CMake
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_FQDN --api-protocol $CI_SERVER_PROTOCOL
  artifacts:
    access: 'developer'

package_linker:
  tags:
    - otus
  when: manual
  inputs:
    build_base_design:
      default: false
      description: Build the base design from scratch?
      type: boolean
  variables:
    SCHEDULER_PARAMETERS: "-A $SLURM_ACCOUNT -p normal -c 1 --mem 16G -t 00:15:00"
    BASE_DESIGN_REF: feature/ci_with_new_linker
  needs:
    - project: $CI_PROJECT_PATH
      job: package_linker
      ref: $BASE_DESIGN_REF
      artifacts: true
  script:
    - cd linker
    # Unzipping the SMBus IP
    - glab -R $CI_PROJECT_PATH securefile download --name "smbus_v1_1-20240328.zip"
    - unzip smbus_v1_1-20240328.zip
    - mv smbus_v1_1-20240328 v80pp/resources/base/iprepo/
    # Building the other IP cores
    - if [ ${{ job.inputs.build_base_design }} = "true" ]; then make -C v80pp/resources/base/iprepo -j16; fi
    # Building the base design
    #- python3 -m v80pp install --jobs 16
    - if [ ${{ job.inputs.build_base_design }} = "true" ]; then echo "Hello World" > v80pp/resources/abstract_shell; fi
    # Packaging the linker
    - pip wheel --no-deps .
  artifacts:
    public: false
    when: always
    paths:
      - linker/install.prj/
      - linker/v80pp/resources/abstract_shell
      - linker/v80pp*.whl

run_linker:
  tags:
    - outs
  needs: package_linker
  variables:
    SCHEDULER_PARAMETERS: "-A $SLURM_ACCOUNT -p normal -c 1 --mem 16G -t 00:15:00"
  script:
    - pip install linker/v80pp*.whl
    - v80++ link -h
